FinalProjectGroup4:
  outputs:
    stg:
      dataset: onlinepayment_stg
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: "iykra-fahmi"
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: onlinepayment_prod
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: "iykra-fahmi"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: prod